---
- name: "JUKEBOX | Install"
  git:
    src: https://github.com/ngollon/jukebox
    version: modipy
    dest: /usr/local/jukebox

- name: "JUKEBOX | Install apt dependencies"
  apt:
    name: [ python3-pillow, python3-dev python3-pip libfreetype6-dev libjpeg-dev build-essential libopenjp2-7 libtiff5 ]  # According to luma.oled
    state: present

- name: "JUKEBOX | Install apt dependencies"
  pip: 
    requirements: /usr/local/jukebox/requirements
    state: present
    virtualenv: /usr/local/jukebox
    virtualenv_command: python3 -m venv

-name: "JUKEBOX | Create library"
  file:
    path: /srv/library
    owner: pi
    group: pi
    state: directory

- name: "JUKEBOX | Copy service file"
  copy:
    src: /usr/local/jukebox/jukebox.service
    dest: /etc/systemd/system/jukebox.service
    remote_src: yes

- name: "JUKEBOX | Start Service"
  service:
    name: jukebox.service
    state: started
    enabled: yes
    daemon-reload: yes