---
- name: "BASIC | Setting hostname"
  hostname:
    name: "{{ hostname }}"

#- name: "BASIC | Allow pi user to access apt"
#  lineinfile:
#    path: /etc/sudoers.d/pi-allow-to-sudo-apt
#    state: present
#    line: "pi ALL=(ALL) NOPASSWD: /usr/bin/apt"
#    validate: /usr/sbin/visudo -cf %s
#    create: yes

- name: "BASIC | Install basic tools"
  apt:
    name: [ man, vim ]    
    state: present

- name: "BASIC | Install shell"
  apt:
    name: [ zsh ]    
    state: present

- name: "BASIC | Configure shell"
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  loop:
    - root
    - pi

- name: "BASIC | Adjust shell config"
  get_url:
    url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
    dest: "{{ item }}/.zshrc"
  loop:
    - /home/pi
    - /root

- name: "BASIC | Install default services"
  apt:
    name: [ cron ]
    state: present

- name: "BASIC | Start and enable default services"
  systemd:
    name: "{{ item }}"
    daemon-reload: yes
    state: started
    enabled: yes
  loop:
    - cron    