---
- name: "MOPIDY | Import package key"
  apt_key:
    url: https://apt.mopidy.com/mopidy.gpg
    state: present

- name: "MOPIDY | Import package sources"
  get_url:
    url: https://apt.mopidy.com/buster.list
    dest: /etc/apt/sources.list.d/mopidy.list

- name: "MOPIDY | Install required packages"
  apt:
    update_cache: yes
    name: [ mopidy, mopidy-mpd, mopidy-spotify, mpc ]
    state: present

- name: "MOPIDY | Install required pip packages"
  pip:    
    executable: /usr/bin/pip3
    name: [ mopidy-iris ]
    state: present
  
- name: "MOPIDY | Configure"
  template: 
    src: mopidy.conf
    dest: /etc/mopidy/mopidy.conf
  
- name: "MOPIDY | Start"
  systemd:
    name: mopidy.service
    state: started
    enabled: yes
    daemon_reload: yes